vms:
  - 1
  - 2
  - 4
  - 8
  - 16
  - 32
max_vms_vtap: 32
max_vms_vf: 32
max_flows: 128
cpus:
  - 1
  - 2
  - 4
  - 8
  - 16
duration: 180
host_ip: 10.0.0.2
sleep_for_vmstart: 10
vm_ip_fmt: 10.0.0.%d
vm_ip_start_vtap: 3
vm_ip_start_vf: 100
host_ip_tail: 2
nic0_mac_fmt: 52:54:00:95:df:%02x
nic1_mac_fmt: 52:54:00:6b:28:%02x
nic1_dev: eth1
image_path: /home/syuu/images
